import 'sources/lib/jira.rb'
import 'sources/lib/slack.rb'
import 'sources/lib/gitflow.rb'
import 'sources/lib/CI.rb'

import 'sources/helper/provisioning_profiles_helper.rb'
import 'sources/helper/match_helper.rb'
import 'sources/helper/unit_testing_helper.rb'
import 'sources/helper/build_number_helper.rb'
import 'sources/helper/changelog_helper.rb'

import "sources/RSBMatch.rb"
import "sources/RSBUpload.rb"
import "sources/RSBWorkflow.rb"

before_all do
  if `gem list -i jira-ruby`.strip == "false"
    sh('gem install jira-ruby')
  end
  require('jira-ruby')
end